# Generated by Django 4.0.3 on 2022-05-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
