# Generated by Django 4.0.3 on 2022-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_email',
            field=models.BooleanField(default=False, verbose_name='이메일 수신 여부'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_phone',
            field=models.BooleanField(default=False, verbose_name='문자메시지 수신 여부'),
        ),
    ]
